package dev.researchhub.workspace.infrastructure;

import dev.researchhub.shared.validation.FieldLengths;
import dev.researchhub.workspace.domain.Workspace;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.UuidGenerator;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA mapping for the {@code workspaces} table created by {@code V3__create_workspaces.sql}.
 *
 * <p>Names are explicit, not derived, so a rename in Java cannot silently diverge from the migration.
 * Flyway owns the schema; Hibernate never creates or alters it (docs/development/persistence.md).
 *
 * <p>Identifiers are UUID v7, generated by the application through Hibernate on insert, the same
 * strategy as {@code UserEntity}. The column has no database default, so there is exactly one place
 * ids come from.
 *
 * <p>{@code createdBy} is a plain {@link UUID} column rather than a {@code @ManyToOne} to
 * {@code UserEntity}: this module must not import {@code user.infrastructure}
 * (docs/development/backend-architecture.md). The reference is still real — the migration declares
 * {@code fk_workspaces_created_by} — it is simply enforced by the database rather than by a mapped
 * association.
 */
@Entity
@Table(name = "workspaces")
public class WorkspaceEntity {

    @Id
    @UuidGenerator(style = UuidGenerator.Style.VERSION_7)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "name", nullable = false, length = FieldLengths.NAME_MAX)
    private String name;

    /** Optional. Null means the workspace has no description; a blank one is stored as null. */
    @Column(name = "description", length = FieldLengths.DESCRIPTION_MAX)
    private String description;

    /** The user who created the workspace. Always the authenticated caller, never a request field. */
    @Column(name = "created_by", nullable = false, updatable = false)
    private UUID createdBy;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Required by JPA. Application code uses {@link #fromDomain(Workspace)}. */
    protected WorkspaceEntity() {
    }

    private WorkspaceEntity(UUID id, String name, String description, UUID createdBy,
                            Instant createdAt, Instant updatedAt) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Maps a domain workspace onto a row. The name and description written here are the ones the
     * domain already trimmed and checked, so a caller cannot bypass those rules by building an entity.
     */
    public static WorkspaceEntity fromDomain(Workspace workspace) {
        return new WorkspaceEntity(
                workspace.id(),
                workspace.name(),
                workspace.description(),
                workspace.createdBy(),
                workspace.createdAt(),
                workspace.updatedAt());
    }

    public Workspace toDomain() {
        return new Workspace(id, name, description, createdBy, createdAt, updatedAt);
    }

    public UUID getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public UUID getCreatedBy() {
        return createdBy;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

}
