/**
 * Jest is used instead of Vitest because Vitest would pull Vite into the toolchain, and this
 * project deliberately does not use Vite (docs/context.md section 5.2). `babel-jest` reuses
 * babel.config.cjs, so tests are transformed exactly like the Webpack build.
 *
 * Component tests opt into jsdom. The source feature and its preview modules have explicit
 * coverage gates alongside the shared API transport checks.
 */
module.exports = {
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  setupFiles: ['<rootDir>/jest.setup.cjs'],
  moduleNameMapper: {
    '\\.module\\.css$': '<rootDir>/jest.css-module.cjs',
    '\\.css$': '<rootDir>/jest.style.cjs',
    '\\.(woff2?|ttf|otf|eot|svg)$': '<rootDir>/jest.asset.cjs',
  },
  testMatch: ['**/*.test.ts', '**/*.test.tsx'],
  collectCoverageFrom: [
    'src/shared/api/**/*.ts',
    '!src/shared/api/index.ts',
    'src/shared/components/**/*.{ts,tsx}',
    'src/shared/hooks/**/*.{ts,tsx}',
    'src/shared/utils/**/*.ts',
    'src/pages/{AppLayoutPage,WorkspaceDetailPage,WorkspaceListPage,SourceRoutePage,SourceDetailPage,DocumentDetailPage,LoginPage,RegisterPage}.tsx',
    'src/features/workspaces/components/{WorkspaceCard,WorkspaceList,CreateWorkspaceForm,CreateWorkspaceDialog}.tsx',
    'src/features/auth/components/AuthLayout.tsx',
    'src/app/{AppRouter,workspaceRoutes}.{ts,tsx}',
    '!src/**/index.ts',
    '!src/**/*.typecheck.tsx',
    'src/features/sources/**/*.{ts,tsx}',
    'src/features/analysis/**/*.{ts,tsx}',
    'src/features/ai/**/*.{ts,tsx}',
    'src/features/documents/api/researchCitation.ts',
  ],
  coverageThreshold: {
    'src/shared/utils/': { lines: 80, branches: 80, functions: 80, statements: 80 },
    'src/pages/WorkspaceListPage.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/pages/SourceDetailPage.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/workspaces/components/WorkspaceCard.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/workspaces/components/WorkspaceList.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/workspaces/components/CreateWorkspaceForm.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/workspaces/components/CreateWorkspaceDialog.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/shared/components/identity/RoleBadge.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/pages/LoginPage.tsx': { lines: 80, branches: 80, functions: 80, statements: 80 },
    'src/pages/RegisterPage.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/auth/components/AuthLayout.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/app/': { lines: 80, branches: 80, functions: 80, statements: 80 },
    'src/pages/SourceRoutePage.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/pages/DocumentDetailPage.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/pages/WorkspaceDetailPage.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/pages/AppLayoutPage.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/shared/components/content/': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/shared/components/navigation/': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/shared/components/shell/': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/shared/components/forms/': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/shared/components/identity/': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/shared/components/overlays/': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/shared/components/feedback/': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/shared/hooks/': { lines: 80, branches: 80, functions: 80, statements: 80 },
    'src/shared/components/': { lines: 80, branches: 80, functions: 80, statements: 80 },
    'src/shared/components/Button.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/shared/components/icons/': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/ai/api/sourceAnalysisApi.ts': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/ai/components/SourceComparisonPanel.tsx': {
      lines: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/documents/api/researchCitation.ts': {
      lines: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/ai/components/AuthoringPanel.tsx': {
      lines: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/ai/api/authoringApi.ts': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/ai/': { lines: 80, branches: 80, functions: 80, statements: 80 },
    'src/features/sources/': { lines: 80, branches: 80, functions: 80, statements: 80 },
    'src/features/sources/components/CsvAssetProfile.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/sources/api/sourceLocations.ts': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/sources/components/PdfSourcePreview.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/sources/components/SourceProcessing.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/sources/components/SourceExtractionPreview.tsx': {
      lines: 80,
      branches: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/sources/api/sourceExtraction.ts': {
      lines: 80,
      functions: 80,
      statements: 80,
    },
    'src/features/analysis/': { lines: 80, branches: 80, functions: 80, statements: 80 },
  },
};
