-- Users: ResearchHub identities.
--
-- Owned by the `user` module (dev.researchhub.user). Authentication mechanics belong to the
-- future `auth` module; see docs/adr/ADR-001-authentication.md. This table stores the identity
-- and a password hash, never a plaintext password.
--
-- Ids are generated by the application (Hibernate @UuidGenerator, UUID v7), so there is
-- deliberately no DEFAULT on `id`. One strategy for every entity; see
-- docs/development/persistence.md.

CREATE TABLE users
(
    id               uuid         NOT NULL,
    -- The address as the user entered it, trimmed. Case is preserved for display and for
    -- sending mail; it is never what uniqueness is decided on.
    email            varchar(254) NOT NULL,
    -- email trimmed and lowercased with Locale.ROOT. The only uniqueness key.
    normalized_email varchar(254) NOT NULL,
    -- Hash of the password, produced by the auth module's password encoder. Never a plaintext
    -- password. Sized for a modern encoder's output including its algorithm/cost prefix.
    password_hash    varchar(255) NOT NULL,
    -- At least FieldLengths.NAME_MAX (255); see docs/development/validation.md.
    display_name     varchar(255) NOT NULL,
    status           varchar(32)  NOT NULL,
    created_at       timestamptz  NOT NULL,
    updated_at       timestamptz  NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),

    -- A user can be disabled or locked out without deleting the row, so workspace history and
    -- authored content keep referring to a real identity.
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED')),

    -- Defence in depth behind the application's own checks: a blank hash would mean an account
    -- with no usable credential, and a blank identity field is never valid.
    CONSTRAINT ck_users_password_hash_not_blank CHECK (length(btrim(password_hash)) > 0),
    CONSTRAINT ck_users_email_not_blank CHECK (length(btrim(email)) > 0),
    CONSTRAINT ck_users_display_name_not_blank CHECK (length(btrim(display_name)) > 0),

    -- The database is what actually guarantees one account per address. Two addresses differing
    -- only by case or surrounding whitespace normalize to the same value and collide here, even
    -- if an application-level check races.
    CONSTRAINT uq_users_normalized_email UNIQUE (normalized_email),

    -- normalized_email must really be the normal form of email; catches a mapping that forgets
    -- to normalize before insert.
    CONSTRAINT ck_users_normalized_email_is_normalized
        CHECK (normalized_email = lower(btrim(normalized_email)))
);

COMMENT ON TABLE users IS
    'ResearchHub identities. Uniqueness is on normalized_email. password_hash is never plaintext.';
