-- Workspaces: the collaboration and security boundary.
--
-- Owned by the `workspace` module (dev.researchhub.workspace). docs/context.md section 8 makes this
-- the main boundary: every workspace-owned entity added later (documents, sources, analyses, AI
-- conversations, audit events) carries a workspace_id referencing this table, and access to those
-- rows is decided by a membership in workspace_members (V4), never by the frontend.
--
-- Ids are generated by the application (Hibernate @UuidGenerator, UUID v7), so there is
-- deliberately no DEFAULT on `id`. One strategy for every entity; see
-- docs/development/persistence.md.

CREATE TABLE workspaces
(
    id          uuid          NOT NULL,
    -- At least FieldLengths.NAME_MAX (255); see docs/development/validation.md.
    name        varchar(255)  NOT NULL,
    -- Optional. At least FieldLengths.DESCRIPTION_MAX (2000). NULL means "no description": the
    -- application normalizes a blank description to NULL so there is one representation of absent,
    -- rather than a mix of NULL and ''.
    description varchar(2000),
    -- The user who created the workspace. A plain uuid column, not a JPA association: the
    -- `workspace` module must not import user.infrastructure (docs/development/backend-architecture.md),
    -- so the reference is enforced here by the database rather than by a mapped entity graph.
    -- User columns are never duplicated onto this table; read them through the `user` module.
    created_by  uuid          NOT NULL,
    created_at  timestamptz   NOT NULL,
    updated_at  timestamptz   NOT NULL,

    CONSTRAINT pk_workspaces PRIMARY KEY (id),

    -- Defence in depth behind the domain's own check: an unnamed workspace is never valid, and a
    -- whitespace-only name would be invisible content in every list that renders it.
    CONSTRAINT ck_workspaces_name_not_blank CHECK (length(btrim(name)) > 0),

    -- The creator must be a real identity, so workspace history keeps pointing at someone. No
    -- ON DELETE clause on purpose: users are disabled through users.status rather than deleted, so
    -- a delete that would orphan a workspace should fail loudly instead of cascading.
    CONSTRAINT fk_workspaces_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

-- PostgreSQL does not index a foreign key automatically, and "workspaces this user created" is a
-- lookup the application makes.
CREATE INDEX ix_workspaces_created_by ON workspaces (created_by);

COMMENT ON TABLE workspaces IS
    'Collaboration and security boundary. Access is granted only through workspace_members.';
