-- Documents: the authored content a workspace exists to produce.
--
-- Owned by the `document` module (dev.researchhub.document). A document belongs to exactly one workspace
-- (docs/context.md section 8), and that is the whole access rule: who may read or edit it is decided by the
-- caller's membership of workspace_id, never by a field on this row. Every query the application makes is
-- scoped by workspace_id, so a document id from another workspace resolves to nothing.
--
-- This is persistence for direct authoring only. docs/context.md section 9 describes a future
-- Tiptap/ProseMirror editor over a Yjs CRDT; none of that is here. There is no document_versions table
-- either — section 20 lists it as a sketch, and history is not this migration's job.
--
-- Ids are generated by the application (Hibernate @UuidGenerator, UUID v7), so there is deliberately no
-- DEFAULT on `id`. See docs/development/persistence.md.

CREATE TABLE documents
(
    id             uuid         NOT NULL,
    -- The workspace that owns this document. No ON DELETE and no ON UPDATE, here or below: a document must
    -- outlive any attempt to remove the rows it points at, because deleting it would destroy authored work
    -- and the provenance docs/context.md sections 3.3 and 3.4 require.
    workspace_id   uuid         NOT NULL,
    -- At least FieldLengths.TITLE_MAX (500); see docs/development/validation.md.
    title          varchar(500) NOT NULL,
    -- How `content` is to be interpreted. Exactly one value is accepted today, and the check constraint is
    -- what keeps a second format from appearing without a migration and a decision.
    content_format varchar(32)  NOT NULL,
    -- The document itself, as JSON. jsonb rather than text so the shape is enforced by the database and a
    -- malformed value cannot be stored at all.
    content        jsonb        NOT NULL,
    -- Optimistic-concurrency token, starting at 1 and incremented on every saved revision. Deliberately a
    -- plain column rather than a Hibernate-managed @Version: the client sends it back on update and sees it
    -- in every response, so a stale write is refused with 409 instead of silently overwriting somebody.
    revision       bigint       NOT NULL,
    -- Who created it. A user id, never a workspace_members id: authorship is a fact about a person and must
    -- survive them leaving the workspace (docs/development/persistence.md).
    created_by     uuid         NOT NULL,
    created_at     timestamptz  NOT NULL,
    updated_at     timestamptz  NOT NULL,
    -- NULL means active. Archiving is soft, exactly as it is for a workspace: the row and its text stay.
    archived_at    timestamptz,

    CONSTRAINT pk_documents PRIMARY KEY (id),

    CONSTRAINT fk_documents_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id),
    CONSTRAINT fk_documents_created_by FOREIGN KEY (created_by) REFERENCES users (id),

    -- Defence in depth behind the domain's own check. An untitled document cannot be told apart in a list.
    CONSTRAINT ck_documents_title_not_blank CHECK (length(btrim(title)) > 0),

    -- Adding a format means widening this constraint in a new migration, the same way ck_workspace_members_role
    -- pins WorkspaceRole. HTML and plain text are not accepted: the content is structured, and a format that
    -- could carry markup would make every renderer a sanitizer.
    CONSTRAINT ck_documents_content_format CHECK (content_format IN ('PROSEMIRROR_JSON')),

    -- A ProseMirror document is an object. A JSON array, string, number, or null is a different thing that
    -- happens to be valid JSON, and none of them is a document.
    CONSTRAINT ck_documents_content_is_object CHECK (jsonb_typeof(content) = 'object'),

    -- Mirrors FieldLengths.DOCUMENT_CONTENT_MAX_BYTES. Measured on PostgreSQL's canonical serialization,
    -- which is not byte-identical to what the client sent — jsonb drops insignificant whitespace and
    -- reorders keys — so this is the same bound applied to the stored form rather than a second opinion on
    -- the request. The application checks the request; this stops anything else.
    CONSTRAINT ck_documents_content_size CHECK (octet_length(content::text) <= 1000000),

    -- Revisions count up from the first saved version.
    CONSTRAINT ck_documents_revision_positive CHECK (revision >= 1)
);

-- "The documents in this workspace" is the only way documents are ever listed, and PostgreSQL does not index
-- a foreign key automatically. Reads by id go through the primary key and are then checked against
-- workspace_id, so no composite index is needed for them.
CREATE INDEX ix_documents_workspace_id ON documents (workspace_id);

COMMENT ON TABLE documents IS
    'Authored workspace content. Access follows workspace_id membership. Archiving is soft; rows are never deleted.';

COMMENT ON COLUMN documents.revision IS
    'Optimistic-concurrency token. The client sends it on update; a mismatch is refused with 409.';
