-- Document versions: coarse restore points for a document, kept until collaborative history exists.
--
-- Owned by the `document` module (dev.researchhub.document). Not every revision is kept. `documents` holds the
-- current text and its revision; a row here is a snapshot of one of those revisions, taken at a milestone:
--
--   CREATED              the first revision, when the document is created
--   MANUAL_SAVE          a save the user asked for explicitly
--   AUTOSAVE_CHECKPOINT  an autosave, when the newest snapshot is older than the configured interval
--                        (researchhub.documents.history.autosave-checkpoint-interval)
--   RESTORE              the new revision produced by restoring an older snapshot
--
-- So typing never produces a row per keystroke, and an autosaving editor still leaves a restore point at least
-- every interval while it is in use.
--
-- History is immutable. A snapshot is inserted once and never changed or removed: tg_document_versions_immutable
-- refuses UPDATE and DELETE for every writer, not only the application. Restoring does not rewrite history
-- either — it saves the old content as a new revision of the document and records that as a RESTORE snapshot
-- pointing at the one it came from.
--
-- Access follows the document, and through it the workspace: there is no workspace_id here, and every read goes
-- through a document that has already been found in the caller's workspace.
--
-- Existing documents get no backfilled snapshot. Their history starts at their next milestone, and nothing in
-- `documents` is rewritten by this migration.
--
-- Ids are generated by the application (Hibernate @UuidGenerator, UUID v7), so there is no DEFAULT on `id`.

CREATE TABLE document_versions
(
    id                       uuid        NOT NULL,
    -- The document this is a snapshot of. No ON DELETE: documents are never deleted, and history must not be
    -- the thing that disappears if somebody tries.
    document_id              uuid        NOT NULL,
    -- The document revision whose content this is. At most one snapshot per revision.
    revision                 bigint      NOT NULL,
    -- Same meaning and same single accepted value as documents.content_format. Stored per snapshot so a future
    -- format is a migration that says what happens to history too, rather than an ambiguity.
    content_format           varchar(32) NOT NULL,
    content                  jsonb       NOT NULL,
    reason                   varchar(32) NOT NULL,
    -- For a RESTORE snapshot, the snapshot whose content was restored. Null for every other reason.
    restored_from_version_id uuid,
    -- Who produced this revision: the saver, or the restorer. A user id, never a membership id.
    created_by               uuid        NOT NULL,
    created_at               timestamptz NOT NULL,

    CONSTRAINT pk_document_versions PRIMARY KEY (id),

    CONSTRAINT fk_document_versions_document FOREIGN KEY (document_id) REFERENCES documents (id),
    CONSTRAINT fk_document_versions_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_document_versions_restored_from
        FOREIGN KEY (restored_from_version_id) REFERENCES document_versions (id),

    -- Also the index for "this document's history, newest first".
    CONSTRAINT uq_document_versions_document_revision UNIQUE (document_id, revision),

    CONSTRAINT ck_document_versions_revision_positive CHECK (revision >= 1),
    CONSTRAINT ck_document_versions_content_format CHECK (content_format IN ('PROSEMIRROR_JSON')),
    CONSTRAINT ck_document_versions_content_is_object CHECK (jsonb_typeof(content) = 'object'),
    -- Mirrors ck_documents_content_size: a snapshot is a copy of a value that already passed it.
    CONSTRAINT ck_document_versions_content_size CHECK (octet_length(content::text) <= 1000000),
    CONSTRAINT ck_document_versions_reason
        CHECK (reason IN ('CREATED', 'MANUAL_SAVE', 'AUTOSAVE_CHECKPOINT', 'RESTORE')),
    -- A RESTORE says where it came from, and nothing else claims to be a restore.
    CONSTRAINT ck_document_versions_restore_source
        CHECK ((reason = 'RESTORE') = (restored_from_version_id IS NOT NULL))
);

CREATE FUNCTION document_versions_are_immutable() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    RAISE EXCEPTION 'document_versions rows are immutable; % is not allowed', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$;

-- Row-level, so it covers every UPDATE and DELETE statement. TRUNCATE is a separate, table-owner operation that
-- no application path issues.
CREATE TRIGGER tg_document_versions_immutable
    BEFORE UPDATE OR DELETE
    ON document_versions
    FOR EACH ROW
EXECUTE FUNCTION document_versions_are_immutable();

COMMENT ON TABLE document_versions IS
    'Immutable restore points for documents, taken at save milestones. Restoring adds a revision; it never deletes history.';

COMMENT ON COLUMN document_versions.restored_from_version_id IS
    'For a RESTORE snapshot, the snapshot whose content became the new revision.';
