-- Sources: research material a workspace member uploaded — the input every later AI and analysis step cites.
--
-- Owned by the `source` module (dev.researchhub.source). A source belongs to exactly one workspace, and that is
-- its whole access rule, exactly as for documents: who may read or add one is decided by the caller's membership
-- of workspace_id. The row holds metadata; the bytes live in object storage under storage_key.
--
-- Three rules this table enforces for every writer, not only the application:
--
--   1. The storage key is opaque and server-generated. It is never derived from the user's filename, so a file
--      name cannot become a path, and it carries no authority: nothing looks a source up by its key.
--   2. The type mapping is closed. source_type is one of the supported types, and media_type is always that
--      type's canonical media type — ck_sources_media_type_matches_type pins the pairs.
--   3. The original input is immutable. id, workspace, file name, type, size, key, hash, uploader, and creation
--      time cannot change (tg_sources_original_is_immutable). Replacing a file later is a new version of the
--      source, not an update of this row; display_name and status are the only fields that move.
--
-- See docs/development/sources.md for the type mapping and the status lifecycle.
--
-- Ids are generated by the application (Hibernate @UuidGenerator, UUID v7), so there is no DEFAULT on `id`.

CREATE TABLE sources
(
    id                uuid          NOT NULL,
    -- No ON DELETE: a source must outlive any attempt to remove what it points at (docs/context.md 3.4).
    workspace_id      uuid          NOT NULL,
    -- What the uploader's file was called, after SourceFilename stripped any path and control characters.
    -- Metadata for people to read. Never used to build a path or a key.
    original_filename varchar(255)  NOT NULL,
    -- What the workspace calls it. Starts as original_filename.
    display_name      varchar(255)  NOT NULL,
    -- The canonical media type of source_type, never the value the client claimed.
    media_type        varchar(128)  NOT NULL,
    source_type       varchar(16)   NOT NULL,
    size_bytes        bigint        NOT NULL,
    -- Where the bytes are, relative to the storage adapter's container. Unique and server-generated.
    storage_key       varchar(255)  NOT NULL,
    -- SHA-256 of the stored bytes, lowercase hex, computed while they were streamed in. What provenance cites.
    content_sha256    varchar(64)   NOT NULL,
    status            varchar(16)   NOT NULL,
    -- A user id, never a membership id: authorship survives somebody leaving the workspace.
    uploaded_by       uuid          NOT NULL,
    created_at        timestamptz   NOT NULL,
    updated_at        timestamptz   NOT NULL,

    CONSTRAINT pk_sources PRIMARY KEY (id),
    CONSTRAINT fk_sources_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id),
    CONSTRAINT fk_sources_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id),
    CONSTRAINT uq_sources_storage_key UNIQUE (storage_key),

    CONSTRAINT ck_sources_source_type CHECK (source_type IN ('PDF', 'DOCX', 'XLSX', 'CSV', 'TXT')),
    CONSTRAINT ck_sources_media_type_matches_type CHECK (
        (source_type = 'PDF' AND media_type = 'application/pdf')
            OR (source_type = 'DOCX'
            AND media_type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')
            OR (source_type = 'XLSX'
            AND media_type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
            OR (source_type = 'CSV' AND media_type = 'text/csv')
            OR (source_type = 'TXT' AND media_type = 'text/plain')
        ),
    CONSTRAINT ck_sources_status CHECK (status IN ('UPLOADED', 'PROCESSING', 'READY', 'FAILED')),
    -- An empty file is not a source. The upper bound mirrors Source.MAX_SIZE_BYTES_CEILING (1 GiB); the
    -- configured per-source limit (researchhub.sources.max-size-bytes) must be at most that.
    CONSTRAINT ck_sources_size_bytes CHECK (size_bytes BETWEEN 1 AND 1073741824),
    -- Exactly the shape StorageKey.generate() produces: a fixed prefix and a random UUID. No file name, no
    -- workspace id, no path separators beyond the prefix, so no traversal.
    CONSTRAINT ck_sources_storage_key_format CHECK (
        storage_key ~ '^sources/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        ),
    CONSTRAINT ck_sources_content_sha256_format CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_sources_original_filename_not_blank CHECK (length(btrim(original_filename)) > 0),
    CONSTRAINT ck_sources_display_name_not_blank CHECK (length(btrim(display_name)) > 0)
);

-- "The sources in this workspace" is how sources are listed, and PostgreSQL does not index a foreign key itself.
CREATE INDEX ix_sources_workspace_id ON sources (workspace_id);

CREATE FUNCTION sources_original_is_immutable() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id
        OR NEW.workspace_id IS DISTINCT FROM OLD.workspace_id
        OR NEW.original_filename IS DISTINCT FROM OLD.original_filename
        OR NEW.media_type IS DISTINCT FROM OLD.media_type
        OR NEW.source_type IS DISTINCT FROM OLD.source_type
        OR NEW.size_bytes IS DISTINCT FROM OLD.size_bytes
        OR NEW.storage_key IS DISTINCT FROM OLD.storage_key
        OR NEW.content_sha256 IS DISTINCT FROM OLD.content_sha256
        OR NEW.uploaded_by IS DISTINCT FROM OLD.uploaded_by
        OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'the original input of source % is immutable; a replacement is a new version', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tg_sources_original_is_immutable
    BEFORE UPDATE
    ON sources
    FOR EACH ROW
EXECUTE FUNCTION sources_original_is_immutable();

COMMENT ON TABLE sources IS
    'Uploaded research material. Access follows workspace_id membership, never storage_key. The original input is immutable.';

COMMENT ON COLUMN sources.storage_key IS
    'Opaque, server-generated object key. Never derived from the filename and never used to authorize.';
