package dev.researchhub.user.infrastructure;

import dev.researchhub.shared.validation.FieldLengths;
import dev.researchhub.user.domain.PasswordHash;
import dev.researchhub.user.domain.User;
import dev.researchhub.user.domain.UserEmail;
import dev.researchhub.user.domain.UserStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.UuidGenerator;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA mapping for the {@code users} table created by {@code V2__create_users.sql}.
 *
 * <p>Names are explicit, not derived, so a rename in Java cannot silently diverge from the
 * migration. Flyway owns the schema; Hibernate never creates or alters it
 * (docs/development/persistence.md).
 *
 * <p>Identifiers are UUID v7, generated by the application through Hibernate on insert. The column
 * has no database default, so there is exactly one place ids come from.
 */
@Entity
@Table(name = "users")
public class UserEntity {

    @Id
    @UuidGenerator(style = UuidGenerator.Style.VERSION_7)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "email", nullable = false, length = FieldLengths.EMAIL_MAX)
    private String email;

    /** Trimmed, lowercased {@link #email}. The unique key; see {@link UserEmail}. */
    @Column(name = "normalized_email", nullable = false, length = FieldLengths.EMAIL_MAX)
    private String normalizedEmail;

    /** Output of a password encoder. Never a plaintext password. */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    @Column(name = "display_name", nullable = false, length = FieldLengths.NAME_MAX)
    private String displayName;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 32)
    private UserStatus status;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Required by JPA. Application code uses {@link #fromDomain(User)}. */
    protected UserEntity() {
    }

    private UserEntity(UUID id, String email, String normalizedEmail, String passwordHash,
                       String displayName, UserStatus status, Instant createdAt, Instant updatedAt) {
        this.id = id;
        this.email = email;
        this.normalizedEmail = normalizedEmail;
        this.passwordHash = passwordHash;
        this.displayName = displayName;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Maps a domain user onto a row. The normal form is taken from {@link UserEmail}, so the value
     * written to {@code normalized_email} is always derived, never supplied by a caller.
     */
    public static UserEntity fromDomain(User user) {
        return new UserEntity(
                user.id(),
                user.email().value(),
                user.email().normalized(),
                user.passwordHash().value(),
                user.displayName(),
                user.status(),
                user.createdAt(),
                user.updatedAt());
    }

    public User toDomain() {
        return new User(
                id,
                new UserEmail(email, normalizedEmail),
                PasswordHash.ofHash(passwordHash),
                displayName,
                status,
                createdAt,
                updatedAt);
    }

    public UUID getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public String getNormalizedEmail() {
        return normalizedEmail;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public String getDisplayName() {
        return displayName;
    }

    public UserStatus getStatus() {
        return status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

}
