package dev.researchhub.shared.error;

public enum ApiErrorCode {
    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    UNAUTHENTICATED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    PAYLOAD_TOO_LARGE,
    UNSUPPORTED_FILE_TYPE,
    UNSUPPORTED_MEDIA_TYPE,
    AI_UNAVAILABLE,
    AI_PROVIDER_ERROR,
    AI_OUTPUT_INVALID,
    AI_REFUSED,
    AI_CONTEXT_TOO_LARGE,
    INTERNAL_ERROR
}
